from django.urls import path
from .views import (home_view, 
                    login_view, 
                    register_view, 
                    logout_view, 
                    dashboard_view, 
                    edit_profile_view, 
                    create_board_view, 
                    edit_board_view, 
                    delete_board_view, 
                    delete_pin_view,
                    board_view,
                    pin_view,
                    like_pin,
                    comment_pin,
                    delete_comment,
                    search_view,
                    user_profile_view,
                    send_friend_request,
                    handle_friend_request,
                    liked_pins_view)

urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('dashboard/', dashboard_view, name='dashboard'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),
    path('board/create/', create_board_view, name='create_board'),
    path('board/edit/<int:bid>/', edit_board_view, name='edit_board'),
    path('board/<int:bid>/delete/', delete_board_view, name='delete_board'),
    path('pin/<int:pinid>/delete/', delete_pin_view, name='delete_pin'),
    path('board/<int:bid>/', board_view, name='view_board'),
    path('pin/<int:pinid>/', pin_view, name='view_pin'),
    path('pin/<int:pinid>/like/', like_pin, name='like_pin'),
    path('pin/<int:pinid>/comment/', comment_pin, name='post_comment'),
    path('comment/<int:cid>/delete/', delete_comment, name='delete_comment'),
    path('search/', search_view, name='search'),
    path('user/<str:username>/', user_profile_view, name='user_profile'),
    path('friend_request/<str:username>/', send_friend_request, name='send_friend_request'),
    path('friend_request/<str:username>/<str:action>/', handle_friend_request, name='handle_friend_request'),
    path('liked-pins/', liked_pins_view, name='liked_pins'),
]
